### ISSUE TITLE
오디션 찾기 - 검색

### ISSUE THREAD

**Issue by gringrape** [ExcelsiorContententsLab/findactor#14]
<img width="882" alt="image" src="https://user-images.githubusercontent.com/53764714/219351797-08f65da5-4348-474a-a1f6-bec41f060d2f.png">

**Comment by gringrape** [comment]
- [ ] 전체 오디션 검색조건 리셋
- [ ] 장르별 조건 적용
- [ ] 제목 및 내용 검색

**Comment by gringrape** [comment]
필터 조건 정리 필요.
기존 필터는 성별에 대해서만 구현이 되어 있음.

**Comment by gringrape** [comment]
```javascript
{
  title: '기업 사내 웹드라마',
  role: '1',
  ageRange: [23, 29],
  productionName: '보르다르 에이젼시',
  prefer: 'G1',
  isScrap: true,
  dueDate: '2023-01-28',
  isOffered: true,
  genre: 'ott',
  gender: '1',
  applicantCnt: 0,
  yesCnt: 1,
  noCnt: 1,
},
```

**Comment by gringrape** [comment]
prefer 를 특기로 쓰고 있음.

**Comment by gringrape** [comment]
조건 필터 수정
- [ ] 성별
- [ ] 특기
- [ ] 나이
- [ ] 신장
- [ ] 장르

**Comment by gringrape** [comment]
신장 정보는 기존의 오디션 자료에 없었음.

**Comment by gringrape** [comment]
검색 조건 -> 제목 및 프로덕션 이름에 대한 검색

**Comment by gringrape** [comment]
오디션 클릭후 상세정보 표시는 다른 작업에서 처리

**Comment by kanghan31** [comment]
안녕하세요 덕수님 고생이 많으십니다 몇가지 말씀 드립니다

1. 오디션 찾기 - 내게 맞는 오디션 찾기 - 나이, 신장 에서 검색 초기화를 하더라도 나이와 신장에서 검색 필터값은 남아 있어서 
수정해야 할거 같습니다 특기는 초기화하면 없어지니 똑같이 가는게 맞을거 같습니다


2. 포트폴리오 수정 항목에서 영상프로필 링크 아직 연결 안된거 같습니다

현재 엑셀에 표기되어 있는 다른 진행과정은 확인이 된거 같습니다

**Comment by gringrape** [comment]
@kanghan31 네 감사합니다. 
1. 검색 초기화 시 정상 작동 확인되는데 혹시 어떤식으로 하셨는지 말씀해주실수 있을까요?

2. 영상 프로필 링크는 별도의 작업으로 잡혀있습니다. 
 https://github.com/ExcelsiorContententsLab/findactor/issues/17
