### ISSUE TITLE
오디션 지원하기

### ISSUE THREAD

**Issue by gringrape** [ExcelsiorContententsLab/findactor#29]
오디션에 지원하면 지원자 목록에 추가 된다.

**Comment by kanghan31** [comment]
안녕하세요 덕수님 
제가 어제 오디션 공고관련 문서를 드렸는데요 지금 와서 다시 보니 제작사측으로 로그인을 하면 오디션 등록 페이지가 있습니다 
그 양식에 맞춰서 드리는게 나은지 아니면 어제 드린 내용에 맞는 양식을 새로 만들어서 드리는게 나은지 싶습니다
이걸 정하고 나서 오디션 등록을 했을때 오디션 공지에 떠야 하는건데 이게 공지에 보여졌을때 또 지금처럼의 공지 모습대로 뜰라고 하면 또 어떠한 방식으로 오디션 등록를 작성해야 하는지 이런 문제들이 파생 되었습니다 확인 되시면 답 주시면 제가 연락 드리겠습니다

이 상황이 배우 프로필과도 같은 문제인데 새로운 양식으로 가느냐 기존의 양식에 맞게 작성을 해서 가느냐 어떤게 효율적인지 싶습니다

**Comment by kanghan31** [comment]
크롬에 탭을 두개 띄워서 배우로그인과 제작사 로그인이 동시에 안 되던데요 이걸 되게 작업하면 시간이 더 걸리는건 당연하겠지만 오래 걸리는 문제일까요? 뭐 중요하고 시급한건 아니니 나중에 마무리 하면서 보아야 할 문제이긴 하는데요  두시간 이상 오래 걸릴 작업이면 안 하는게 나을거 같습니다

**Comment by gringrape** [comment]
> 크롬에 탭을 두개 띄워서 배우로그인과 제작사 로그인이 동시에 안 되던데요 이걸 되게 작업하면 시간이 더 걸리는건 당연하겠지만 오래 걸리는 문제일까요? 뭐 중요하고 시급한건 아니니 나중에 마무리 하면서 보아야 할 문제이긴 하는데요 두시간 이상 오래 걸릴 작업이면 안 하는게 나을거 같습니다

한시간 정도 걸릴것 같은데, 다른 것들하고 우선순위를 보면 좋을것 같아요.

**Comment by gringrape** [comment]
## 서버 작업 
- [ ] 간단한 express.js 서버 작성 
- [ ] Dockerize
- [ ] AWS 배포
- [ ] 오디션 지원 기능 
- [ ] 오디션 entity 추가 -> 제작사 one to many 
- [ ] 오디션에 지원자 추가 -> 지원자 one to many

**Comment by gringrape** [comment]
- [ ] 오디션 지원 API => 오디션 id, userId 필요
- [ ] 오디션 entity 추가 -> 제작사 one to many 
- [ ] 오디션에 지원자 추가 -> 지원자 one to many 
- [ ] 오디션 목록 API

**Comment by gringrape** [comment]
Dockerize
https://nodejs.org/en/docs/guides/nodejs-docker-webapp/

**Comment by gringrape** [comment]
fake REST API

https://www.npmjs.com/package/json-server

**Comment by gringrape** [comment]
JSON file database

https://www.npmjs.com/package/lowdb

**Comment by gringrape** [comment]
AWS launch instance

**Comment by gringrape** [comment]
배포 도메인 - http://findactor.shop:8080/

**Comment by gringrape** [comment]
https://velog.io/@server30sopt/EC2-HTTPS%EB%A1%9C-%EC%97%B0%EA%B2%B0%ED%95%98%EA%B8%B0

**Comment by gringrape** [comment]
CORS 
https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API/Using_Fetch

**Comment by gringrape** [comment]
오디션에 지원하면 제작사의 지원리스트에 추가된다.

**Comment by gringrape** [comment]
- [ ] 오디션 지원 API 
- [ ] 지원 API 호출

**Comment by gringrape** [comment]
필요정보
```javascript
{
  name: '최창환',
  gender: 'male',
  age: '36',
  height: '178',
  weight: '65',
  imgSrc: '/assets/findActor/1.jpg',
}
```
