### ISSUE TITLE
로그인 화면 

### ISSUE THREAD

**Issue by gringrape** [ExcelsiorContententsLab/findactor#6]
<img width="1276" alt="image" src="https://user-images.githubusercontent.com/53764714/218653984-87106a44-4b35-42ad-90f8-fd119dc34c6e.png">

**Comment by gringrape** [comment]
- 배우, 제작사 로그인 
- 로그인 하지 않고 접근시 메인으로 보내기

**Comment by kanghan31** [comment]
로그인

**Comment by gringrape** [comment]
URL 변경 
- 로그인 화면 => `/login`

**Comment by gringrape** [comment]
router
`index.js`:
```javascript
    // 로그인
    {
      path: '/login',
      name: 'login',
      component: LoginView,
    },

```

**Comment by gringrape** [comment]
스타일 적용 - scoped CSS
https://vuejs.org/api/sfc-css-features.html#scoped-css

**Comment by gringrape** [comment]
구성 참고 
https://5friday.kr/login.do

**Comment by kanghan31** [comment]
구성 참고
https://5friday.kr/login.do

링크는 연결이 안되는데 
작업 경과를 보여 주시는거죠?

**Comment by gringrape** [comment]
회원가입 폼 스타일 적용
<img width="1228" alt="image" src="https://user-images.githubusercontent.com/53764714/218747106-c840858f-2889-48be-bdf8-da1eb24a5913.png">

**Comment by gringrape** [comment]
+ 푸터
<img width="1245" alt="image" src="https://user-images.githubusercontent.com/53764714/218755575-ba44998d-ab9f-4ab7-a3b7-a8d8e941a8e7.png">

**Comment by gringrape** [comment]
로그인 메커니즘 체크
- 핸들러
- localStorage

**Comment by gringrape** [comment]
인가 메커니즘 체크
- 페이지 진입시 인터셉터

**Comment by gringrape** [comment]
> Note: Inside of a Vue instance, you have access to the router instance as $router. You can therefore call this.$router.push.

**Comment by gringrape** [comment]
`LoginVue`:
```
  methods: {
    login() {
      if (this.username === 'actor@example.com' && this.password === '1234') {
        this.$router.push('/');
        return;
      }

      if (this.username === 'production@example.com' && this.password === '1234') {
        this.$router.push('/production');
        return;
      }

      alert('아이디 또는 비밀번호를 확인하세요!');
    },
  },

```

**Comment by gringrape** [comment]
로컬 스토리지 - https://gist.github.com/lorisleiva/ac21f8492f9e74ddb8a565e054188d1c

**Comment by gringrape** [comment]
인가 적용 - Navigation guard

**Comment by gringrape** [comment]
로그인 하지 않고 접근시

<img width="1043" alt="image" src="https://user-images.githubusercontent.com/53764714/218781574-291a6f81-c2a3-4d6b-bc88-d7d3fb6a2e75.png">

**Comment by gringrape** [comment]
로그아웃 시 토큰 삭제.

**Comment by gringrape** [comment]
- 배우 아이디, 비번 - `actor@example.com`, 1234
- 제작사 아이디, 비번 - `production@example.com`, 1234

**Comment by gringrape** [comment]
@kanghan31 
https://findactor.kr 에서 로그인 기능 테스트 가능합니다. 
아래 항목 보시고 말씀주세요.
https://github.com/ExcelsiorContententsLab/findactor/issues/6#issuecomment-1429943737

**Comment by gringrape** [comment]
경로 변경으로 필모그래피와 프로필은 이미지가 안나올거에요. 
이건 다음작업(프로필 수정)에서 이미지 업로드로 대체할 예정입니다.

**Comment by kanghan31** [comment]
다음 작업 
1. 오른쪽 상단의 연기자 사용자 연결 화면
2. 오디션 찾기
우선은 위 순서가 될거 같습니다

**Comment by gringrape** [comment]
id: testactor120@gmail.com
password: 1234 

id: testproduction120@gmail.com
password: 5678

**Comment by gringrape** [comment]
- GitHub Action 권한 수정
repository 에서 `GITHUB_TOKEN`에 대한 기본 권한을 설정 가능하고, github action 의 workflow 에서 변경이 가능함.
https://github.com/peaceiris/actions-gh-pages#github-enterprise-server-support

**Comment by gringrape** [comment]
기존의 문제는 push 과정에서만 deploy 가 일어나도록 변경함.
