### ISSUE TITLE
배우 포트폴리오 수정

### ISSUE THREAD

**Issue by gringrape** [ExcelsiorContententsLab/findactor#7]
## 요구사항
- 영상 프로필 추가/삭제 
- 영상 프로필 추가시 이미지도 추가.
- 이미지 프로필 추가/삭제
- 작품 경력 삭제
- 임시저장 버튼 삭제

**Comment by gringrape** [comment]
취소를 누르면 변경사항 초기화. 
등록하기를 눌러야 반영

**Comment by gringrape** [comment]
메인화면에서 해당 배우의 프로필 변화가 확인되도록.

**Comment by gringrape** [comment]
메인화면에서 추가하기 버튼, 작품 경력 삭제

**Comment by gringrape** [comment]
## 작업 구상 
- 배우의 프로필, 필모그래피를 반환하는 간단한 서버 구상. => 간단한 express 복잡함...
- 혹은 로컬 스토리지에 데이터를 구조화시켜 저장할 수 있는 구조.
- 레포지토리 형태로 스토리지 관리.

**Comment by gringrape** [comment]
준비물 
- S3 
- 로컬스토리지 as database
- S3 image uploader

**Comment by gringrape** [comment]
https://github.com/knadh/localStorageDB

**Comment by gringrape** [comment]
이미지 업로더: https://www.npmjs.com/package/s3-image-uploader

**Comment by gringrape** [comment]
## 데이터
- `Actor` - `accessToken`, `avatars`, `filmography`

**Comment by gringrape** [comment]
S3 설정
<img width="287" alt="image" src="https://user-images.githubusercontent.com/53764714/218881004-c7b830dc-c5e8-4d72-8ef2-70515a501ac5.png">

**Comment by gringrape** [comment]
업로드 시 이미지 압축 - webp 형식 => 추후 작업(로딩 속도 개선)에서 고려.

**Comment by gringrape** [comment]
S3 업로드 - https://findactor.s3.ap-northeast-2.amazonaws.com/250px-Song_Gangho_2016.jpeg

**Comment by gringrape** [comment]
AWS 클라이언트 - https://www.npmjs.com/package/aws-s3

**Comment by gringrape** [comment]
## 기술 검증
이미지 업로드와 로컬 스토리지 데이터 베이스를 활용하는 예시 프로젝트 구성 필요

**Comment by gringrape** [comment]
=> 어플리케이션 초기화 시 데이터 시드 과정이 필요.

**Comment by gringrape** [comment]
- [ ] 이미지 업로드 인터랙션
- [ ] 클라이언트를 이용한 S3 업로드 - 이미지 주소 얻기 
- [ ] 이미지 프로필 데이터를 db에 추가

**Comment by gringrape** [comment]
DB 시드 방법 
- 시드는 최초의 1회
- 초기화 되었는지 여부 확인

**Comment by gringrape** [comment]
이미지 인터랙션
<img width="724" alt="image" src="https://user-images.githubusercontent.com/53764714/219010605-e1c7418a-f859-425b-b397-86d81e8b895e.png">

**Comment by gringrape** [comment]
AWS lambda 활용.

응답형식 
```json
{
"name": "xxx.png",
"status": "done",
"url": "https://zos.alipayobjects.com/rmsportal/jkjgkEfvpUPVyRjUImniVslZfWPnJuuZ.png",
"thumbUrl": "https://zos.alipayobjects.com/rmsportal/jkjgkEfvpUPVyRjUImniVslZfWPnJuuZ.png"
}
```

**Comment by gringrape** [comment]
AWS lambda 함수
<img width="1202" alt="image" src="https://user-images.githubusercontent.com/53764714/219015811-12ae0eee-5206-4b06-ac59-62af4aa39bcc.png">

**Comment by gringrape** [comment]
http 요청을 받을수 있는 설정 필요.

**Comment by gringrape** [comment]
simple lambda test 
- 기본적인 GET 요청 수행
- lambda 권한 설정 -> public

**Comment by gringrape** [comment]
Lambda 기본적인 GET 요청
- configuration -> function url - https://afpogo7a7ravav27gluo5gyum40omcrk.lambda-url.ap-northeast-1.on.aws/

**Comment by gringrape** [comment]
권한 설정 체크.
- permission 항목(역할, 정책)을 적절하게 설정하지 않은 경우 오류

```json
{
  "Message": "Forbidden"
}
```

**Comment by gringrape** [comment]
CORS 설정
- 간단한 라이브 서버 
- GET 요청시 실패 -> CORS 가 설정되어 있지 않으므로.

**Comment by gringrape** [comment]
POST 요청도 해보기. 

실패, CORS 오류.
<img width="649" alt="image" src="https://user-images.githubusercontent.com/53764714/219113075-67d2ab7e-19e4-4b99-b361-13ba12d553e2.png">

**Comment by gringrape** [comment]
CORS 구성. 
API 게이트 웨이 추가 -> 메서드추가 -> CORS 설정. 

POST 요청 성공.
<img width="410" alt="image" src="https://user-images.githubusercontent.com/53764714/219114330-a03e6a40-a7d1-4aeb-bf47-b444d343110e.png">

**Comment by gringrape** [comment]
파일 업로드 실험. 
요청 자체는 성공함. 
<img width="436" alt="image" src="https://user-images.githubusercontent.com/53764714/219114988-1660da12-8332-4883-8d42-8bcf3e7f8efc.png">

**Comment by gringrape** [comment]
AWS Gateway => multipart/form 지원 설정.

**Comment by gringrape** [comment]
API Gateway -> multipart/form-data에 대한 패스 스루 설정.
https://devlog-wjdrbs96.tistory.com/331

**Comment by gringrape** [comment]
IAM role 추가

**Comment by gringrape** [comment]
lambda URL: https://9shbrlwx14.execute-api.ap-northeast-1.amazonaws.com/default/uploadImage

**Comment by gringrape** [comment]
a-upload 로 요청

```javascript
  <a-upload
      v-model:file-list="fileList"
      action="https://9shbrlwx14.execute-api.ap-northeast-1.amazonaws.com/default/uploadImage"
      list-type="picture-card"
      @preview="handlePreview"
  >

```

**Comment by gringrape** [comment]
multipart/form-data 설정.

**Comment by gringrape** [comment]
<img width="634" alt="image" src="https://user-images.githubusercontent.com/53764714/219260012-70e59920-65bc-461a-bfe0-7b17abb7da74.png">

**Comment by gringrape** [comment]
- [ ] 이미지 업로드 인터랙션 추가
- [ ] 추가 상태 관찰
- [ ] 영속화
<img width="526" alt="image" src="https://user-images.githubusercontent.com/53764714/219267583-ad34760f-e222-4c1e-8ba6-324acb167161.png">

**Comment by gringrape** [comment]
인터랙션
<img width="511" alt="image" src="https://user-images.githubusercontent.com/53764714/219276608-7f4d8557-2971-4d0f-9be0-d5bd0b5be680.png">

**Comment by gringrape** [comment]
- [ ] 이미지 프로필 제거
- [ ] 이미지 프로필 추가

**Comment by gringrape** [comment]
영속화 
- [ ] 시딩
- [ ] 마운트 시에 스토리지 불러오기.
- [ ] 저장하기를 누를경우에만 스토리지에 반영하기.

**Comment by gringrape** [comment]
- [ ] 등록하기를 누르면 배우 메인으로 이동
- [ ] 코드 정리

**Comment by gringrape** [comment]
## 작업 내용
- 이미지 업로드 서버 구축
- 필모그래피 추가/제거
- 이미지 프로필 추가/제거
- 등록하기

**Comment by kanghan31** [comment]
영상 프로필에서 영상URL에 링크를  넣고 등록한 후 클릭했을때 링크로 넘어가야 할거 같은데 안 넘어 갑니다

**Comment by kanghan31** [comment]
왼쪽 상단의 파인드액터를 클릭했을때 로그인 메인 화면으로 날아 가는것을 로그인 다음 화면 메인 화면으로 가게끔 해 줘야 할거 같습니다

**Comment by gringrape** [comment]
@kanghan31 네 포스터를 클릭하면 영상주소로 이동하는 걸 말씀하시는거죠?

**Comment by gringrape** [comment]
> 왼쪽 상단의 파인드액터를 클릭했을때 로그인 메인 화면으로 날아 가는것을 로그인 다음 화면 메인 화면으로 가게끔 해 줘야 할거 같습니다

네 맞습니다. 이 부분은 확인한 후에 작업 등록해두었습니다 
https://github.com/ExcelsiorContententsLab/findactor/issues/9

**Comment by kanghan31** [comment]
> 

네네 맞습니다  전에 있는 각 해당하는 포스터 링크는 제가 보내 드릴게요

**Comment by kanghan31** [comment]
강철비 2  https://movie.naver.com/movie/bi/mi/basic.naver?code=188909

가장 보통의 연애 https://movie.naver.com/movie/bi/mi/basic.naver?code=182205

마약왕 https://movie.naver.com/movie/bi/mi/basic.naver?code=157297

밤의 문이 열린다 https://movie.naver.com/movie/bi/mi/basic.naver?code=176625

**Comment by kanghan31** [comment]
로그인 화면 로고도 수정도 부탁드려요~
